Word: 'Donut'
# This is a comment :O
Number: 808
Boolean: true
String-list:
  - 'Value1'
  - 'Value2'
  - 'Value3'

Double: 5.2

Test:
  Test1:
  Test2:
    Test2.1:
      # Test.Test2.Test2.1
  Test3:
    # Test.Test3